Repository yatulearn/yatulearn, pull requests merged in 2024-10, with the labels that each got.

#18 Added and modified contents in AIML section
  Evolution-of-AI.png
  ethical.png
  types-of-artificial-intelligence.jpg
  types-of-ml.png
  yatu_learn_aiml.css
  yatu_learn_aiml.html
Labels: gssoc-ext, hacktoberfest, Level 1, hacktoberfest-accepted

#25 Task Done
  README.md
  YatuLearn.png
Labels: gssoc-ext, hacktoberfest, Level 1, hacktoberfest-accepted

#60 Fix for Roadmap Button Functionality and Styling
  index.html
  js/script.js
Labels: gssoc-ext, hacktoberfest, hacktoberfest-accepted, Level 2

#79 Update Scrollbar | Issue #71
  css/sidebar.css
  css/yatu_learn_aiml.html
  index.html
  pages/construction.html
  pages/privacy_learn.html
  pages/yatu_learn_about.html
  pages/yatu_learn_aiml.html
  pages/yatu_learn_cn.html
  pages/yatu_learn_cs.html
  pages/yatu_learn_dsa.html
  pages/yatu_learn_notes.html
  pages/yatu_learn_os.html
  pages/yatu_learn_qp.html
  pages/yatu_learn_wd.html
Labels: gssoc-ext, hacktoberfest, Level 1, hacktoberfest-accepted

#57 Added All Contributors' Profile Photos
  README.md
Labels: gssoc-ext, hacktoberfest, Level 1, hacktoberfest-accepted

#30 styled topic cards and added hover effect to topic cards
  assets/1704439037481.png
  assets/CN-1.png
  assets/application-smartphone-business.png
  assets/data-structures-and-algorithms.png
  assets/kazan-russia-april-11-2017-260nw.png
  assets/lock-network-technology-concept.png
  assets/website-development-banner_33099.png
  css/style.css
  css/yatu_learn_about.css
  index.html
Labels: gssoc-ext, hacktoberfest, Level 1, hacktoberfest-accepted

#65 favicon added
  index.html
Labels: gssoc-ext, hacktoberfest, Level 1, hacktoberfest-accepted

#69 Additon of All Contributors Photos | Issue 66
  README.md
Labels: gssoc-ext, hacktoberfest, Level 1, hacktoberfest-accepted

#90 Enhanced the UI of Pop up on hovering question paper item in navbar
  css/style.css
Labels: gssoc-ext, hacktoberfest, Level 1, hacktoberfest-accepted

#83 Fixed back to home page button and logo
  index.html
  js/script.js
Labels: gssoc-ext, hacktoberfest, Level 1, hacktoberfest-accepted

#85 PR for [Enhancement] Adding subsections in Notes page - issue #19
  css/yatu_learn_notes.css
  js/yatu_learn_script.js
  pages/yatu_learn_notes.html
Labels: gssoc-ext, hacktoberfest, hacktoberfest-accepted, Level 3

#105 added on-hover-color change feature to Social Icons.
  css/style.css
  index.html
Labels: gssoc-ext, hacktoberfest, Level 1, hacktoberfest-accepted

#123 Question paper button hover corrected #115
  css/style.css
  index.html
Labels: gssoc-ext, hacktoberfest, Level 1, hacktoberfest-accepted

#120 Update the DSA Page | #87
  css/yatu_learn_dsa.css
  pages/yatu_learn_dsa.html
Labels: gssoc-ext, hacktoberfest, Level 1, hacktoberfest-accepted

#128 Added search bar according to new notes page
  css/yatu_learn_notes.css
  pages/yatu_learn_notes.html
Labels: gssoc-ext, hacktoberfest, hacktoberfest-accepted, Level 2

#130 Added the recomended resources section in all the courses
  pages/yatu_learn_aiml.html
  pages/yatu_learn_cn.html
  pages/yatu_learn_cs.html
  pages/yatu_learn_dsa.html
  pages/yatu_learn_os.html
  pages/yatu_learn_wd.html
Labels: gssoc-ext, hacktoberfest, Level 1, hacktoberfest-accepted

#150 Fix: Body Overflow in y-direction- Adjust Flex Direction for Buttons
  css/style.css
Labels: gssoc-ext, hacktoberfest, hacktoberfest-accepted, Level 2

#159 Add Favicon in All the HTML Pages
  index.html
  pages/construction.html
  pages/privacy_learn.html
  pages/yatu_learn_about.html
  pages/yatu_learn_aiml.html
  pages/yatu_learn_cn.html
  pages/yatu_learn_cs.html
  pages/yatu_learn_dsa.html
  pages/yatu_learn_notes.html
  pages/yatu_learn_os.html
  pages/yatu_learn_qp.html
  pages/yatu_learn_wd.html
  yatu_learn_aiml.html
  yatu_learn_cn.html
  yatu_learn_cs.html
  yatu_learn_dsa.html
  yatu_learn_os.html
  yatu_learn_wd.html
Labels: gssoc-ext, hacktoberfest, Level 1, hacktoberfest-accepted

#178 Necessary changes to improve code quality
  js/script.js
Labels: gssoc-ext, hacktoberfest, Level 1, hacktoberfest-accepted

#169 Updation of AboutUs Page with Responsiveness | Issue #46
  css/yatu_learn_about.css
  pages/yatu_learn_about.html
Labels: gssoc-ext, hacktoberfest, Level 1, hacktoberfest-accepted

#168 Fixes #134
  pages/yatu_learn_os.html
  pages/yatu_learn_qp.html
  pages/yatu_learn_wd.html
Labels: gssoc-ext, hacktoberfest, Level 1, hacktoberfest-accepted

#196 #165 Added LICENSE File in Root Directory
  LICENSE.txt
Labels: gssoc-ext, hacktoberfest, level1, hacktoberfest-accepted

#235 Update README.md #208
  README.md
Labels: gssoc-ext, hacktoberfest, level1, hacktoberfest-accepted

#219 About us page redisgned : done #161 about us page UI redesigned.
  assets/mission.jpg
  assets/origin.png
  assets/vision.png
  css/yatu_learn_about.css
  js/yatu_learn_countup.js
  pages/yatu_learn_about.html
Labels: gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#220 Fix The NavBar Issue
  css/style.css
  index.html
Labels: gssoc-ext, hacktoberfest, level1, hacktoberfest-accepted

#207 Fix Padding for Banner Section and Change Navbar Items Color for Better Contrast
  css/yatu_learn_about.css
Labels: gssoc-ext, hacktoberfest, level1, hacktoberfest-accepted

#252 Fix Mobile Overflow Caused by Road Buttons Section
  css/style.css
Labels: gssoc-ext, hacktoberfest, level1, hacktoberfest-accepted

#276 spelling corrected
  index.html
Labels: gssoc-ext, hacktoberfest, level1, hacktoberfest-accepted

#279 Added Dockerfile for containerization and Update README for Containerization
  Dockerfile
  README.md
Labels: gssoc-ext, hacktoberfest, level1, hacktoberfest-accepted

#245 Addition of B2T | Issue #70
  css/B2T.css
  css/style.css
  index.html
  js/B2T.js
  pages/privacy_learn.html
  pages/yatu_learn_about.html
  pages/yatu_learn_aiml.html
  pages/yatu_learn_cn.html
  pages/yatu_learn_cs.html
  pages/yatu_learn_dsa.html
  pages/yatu_learn_notes.html
  pages/yatu_learn_os.html
  pages/yatu_learn_qp.html
  pages/yatu_learn_wd.html
Labels: gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#240 Updation of Questions Papers UI | Issue #118
  pages/yatu_learn_qp.html
Labels: gssoc-ext, hacktoberfest, hacktoberfest-accepted, level3

#242 Addition of FAQs | Issue #88
  css/yatu_learn_about.css
  js/FAQs.js
  pages/yatu_learn_about.html
Labels: gssoc-ext, hacktoberfest, level1, hacktoberfest-accepted

#349 Add mini chatbot
  boy.png
  chatbot.gif
  chatbot.html
  css/style.css
  index.html
  pages/boy.png
  pages/chatbot.gif
  pages/chatbot.html
  pages/yatu_learn_about.html
  pages/yatu_learn_notes.html
  pages/yatu_learn_qp.html
Labels: gssoc-ext, hacktoberfest, hacktoberfest-accepted, level3

#222 Fix alignment on About page
  css/yatu_learn_about.css
  pages/yatu_learn_about.html
Labels: gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#312 Added smooth image load-in animation with subtle hover effect
  css/style.css
Labels: gssoc-ext, hacktoberfest, level1, hacktoberfest-accepted

#320 added rate me popup modal at footer
  css/style.css
  index.html
  js/script.js
Labels: gssoc-ext, hacktoberfest, level1, hacktoberfest-accepted

#463 STYLE IMPROVED
  css/style.css
  js/script.js
  pages/yatu_learn_about.html
Labels: gssoc-ext, level1
